# Site settings
title: Einar Holsbø
email: einar@cs.uit.no
description: > # this means to ignore newlines until "baseurl:"
  Ph. D. student at the University of Tromsø, Norway. Interested in machine
  learning, statistics, distributed systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://3inar.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  3inar

# Build settings
markdown: kramdown
